/// <reference lib="webworker" />

// @ts-expect-error: Ignore missing module error during development/build
import { build, files, version } from '$service-worker';
// @ts-expect-error: Ignore missing module error during development/build
import { resolveRoute } from '$app/paths';

const CACHE_NAME = `cache-${version}`;

// Add all files from $service-worker to the cache
// build includes files generated by Vite (JS, CSS)
// files includes files in your static directory
const ASSETS_TO_CACHE = build.concat(files);

self.addEventListener('install', (event) => {
  console.log('[Service Worker] Install event');
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => {
        console.log('[Service Worker] Opened cache:', CACHE_NAME);
        return cache.addAll(ASSETS_TO_CACHE);
      })
      .then(() => {
        console.log('[Service Worker] All assets cached. Skip waiting.');
        (self as unknown as ServiceWorkerGlobalScope).skipWaiting();
      })
      .catch(err => {
        console.error('[Service Worker] Cache addAll failed:', err);
      })
  );
});

self.addEventListener('activate', (event) => {
  console.log('[Service Worker] Activate event');
  event.waitUntil(
    caches.keys().then(async (cacheNames) => {
      await Promise.all(
        cacheNames.map(async (cacheName) => {
          if (cacheName !== CACHE_NAME) {
            console.log('[Service Worker] Deleting old cache:', cacheName);
            await caches.delete(cacheName);
          }
        })
      );
      console.log('[Service Worker] Claiming clients.');
      await (self as unknown as ServiceWorkerGlobalScope).clients.claim();
    })
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;

  // Ignore non-GET requests
  if (request.method !== 'GET') {
    return;
  }

  // For navigation requests (HTML pages), try network first, then cache.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          // Try network first
          const networkResponse = await fetch(request);
          // If the fetch was successful, cache the response for future offline use
          // Only cache http/https requests
          if (request.url.startsWith('http') && networkResponse && networkResponse.status === 200 && networkResponse.type === 'basic') {
            const responseToCache = networkResponse.clone();
            caches.open(CACHE_NAME).then(cache => {
              console.log('[Service Worker] Caching new navigation response:', request.url);
              cache.put(request, responseToCache);
            });
          }
          return networkResponse;
        } catch (error) {
          // Network failed, try to serve the app shell from cache
          console.log('[Service Worker] Network fetch failed for navigation. Attempting to serve app shell from cache.', request.url, error);
          const cache = await caches.open(CACHE_NAME);
          
          // Attempt to retrieve the main application page (shell)
          // Common paths for SPAs are '/' or '/index.html'
          let cachedResponse = await cache.match(resolveRoute('/', {}));
          if (!cachedResponse) {
            cachedResponse = await cache.match(resolveRoute('/index.html', {}));
          }

          // const cachedResponse = await cache.match(request);
          if (cachedResponse) {
            // App shell found in cache, return it
            console.log('[Service Worker] Serving app shell from cache for failed navigation.', cachedResponse.url);
            return cachedResponse;
          } else {
            // App shell not found in cache.
            // Instead of returning a custom "You are offline" message,
            // let the browser handle it as a standard network failure for the navigation request.
            console.warn('[Service Worker] App shell not found in cache for failed navigation. Browser will display default offline page.', request.url);
            // Returning undefined signals that the service worker is not handling this fetch event,
            // allowing the browser to use its default network error handling (e.g., show an offline page).
            return new Response('You are offline. Please check your internet connection.', {
              status: 408,
              headers: { 'Content-Type': 'text/plain' },
            });return undefined;
          }
        }
      })()
    );
    return; // End handling for navigate requests
  }

  // For other requests (assets like JS, CSS, images), use a cache-first strategy.
  // Serve from cache if available, otherwise fetch from network and optionally cache.
  event.respondWith(
    caches.match(request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }
      return fetch(request).then((networkResponse) => {
        // Cache new assets dynamically if they weren't part of the initial ASSETS_TO_CACHE
        // Only cache http/https requests
        if (request.url.startsWith('http') && networkResponse && networkResponse.status === 200 && networkResponse.type === 'basic') {
          const responseToCache = networkResponse.clone();
          caches.open(CACHE_NAME).then(cache => {
            console.log('[Service Worker] Caching new asset:', request.url);
            cache.put(request, responseToCache);
          });
        }
        return networkResponse;
      }).catch(error => {
        console.error('[Service Worker] Fetch failed for asset:', request.url, error);
        // For assets, if not in cache and network fails, it results in a broken resource.
        // You could return a placeholder image/style if appropriate.
      });
    })
  );
});
